spring:
  server:
    port: ${PORT:8080}
  datasource:
    url: jdbc:postgresql://dpg-d2cvhchr0fns73ebmebg-a.oregon-postgres.render.com/ww2_db_bv1z
    username: ww2_db_bv1z_user
    password: REVhHnDHazWh3QoGatGT6LLCIBzLrzqU
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  application:
    name: ww2-service

logging:
  level:
    com.peter.save_bulgaria: INFO
    org.springframework.security: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/save-bulgaria.log

server:
  port: ${PORT:8080}
  address: 0.0.0.0
  error:
    include-message: always
    include-binding-errors: always